# Generated by Django 5.2.4 on 2025-07-14 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('organizer_name', models.CharField(max_length=100)),
                ('organizer_email', models.EmailField(max_length=254)),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('conference', 'Conference'), ('webinar', 'Webinar'), ('workshop', 'Workshop'), ('other', 'Other')], default='meeting', help_text='Type of event being booked', max_length=50)),
                ('attendance', models.PositiveIntegerField(help_text='Expected number of attendees')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the event', max_length=20)),
                ('space', models.CharField(blank=True, help_text='Venue or location of the event', max_length=100)),
                ('user', models.ForeignKey(help_text='User who created the event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
