# Generated by Django 5.2.3 on 2025-07-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('conference', 'Conference'), ('webinar', 'Webinar'), ('workshop', 'Workshop')], default='meeting', help_text='Type of event being booked', max_length=50),
        ),
    ]
